exports.seasonMap = new Map()
    .set("The Red War", 1)
    .set("Curse of Osiris", 2)
    .set("Warmind", 3)
    .set("Forsaken", 4)
    .set("Outlaw", 4)
    .set("Forge", 5)
    .set("Drifter", 6)
    .set("Opulence", 7)
    .set("Shadowkeep", 8)
    .set("Undying", 8)
    .set("Dawn", 9)
    .set("Worthy", 10)
    .set("Arrivals", 11)
    .set("Beyond Light", 12)
    .set("Hunt", 12)
    .set("Chosen", 13)
    .set("Splicer", 14)
    .set("Lost", 15)
    .set("30th Anniversary", 15)
    .set("The Witch Queen", 16)
    .set("Risen", 16)
    .set("Haunted", 17)
    .set("Plunder", 18)
    .set("Seraph", 19)
    .set("Lightfall", 20)
    .set("Defiance", 20)
    .set("Deep", 21)
    .set("Witch", 22)
    .set("Wish", 23)

exports.masterworks = ['Impact', 'Range', 'Stability', 'Handling', 'Reload', 'Magazine', "Blast Radius", 'Velocity', "Draw Time", "Charge", "Accuracy", "Shield Duration"]

exports.sections = ['scopes', 'sights', 'barrels', 'bowstrings', 'hafts', 'blades', 'batteries', 'magazines', 'guards', 'arrows', 'trait1', 'trait2', 'origin', 'grips', 'stocks', 'masterwork', 'mod']
