exports.seasonMap = new Map()
    .set('The Red War', 1)
    .set('Curse of Osiris', 2)
    .set('Warmind', 3)
    .set('Forsaken', 4)
    .set('Outlaw', 4)
    .set('Forge', 5)
    .set('Drifter', 6)
    .set('Opulence', 7)
    .set('Shadowkeep', 8)
    .set('Undying', 8)
    .set('Dawn', 9)
    .set('Worthy', 10)
    .set('Arrivals', 11)
    .set('Beyond Light', 12)
    .set('Hunt', 12)
    .set('Chosen', 13)
    .set('Splicer', 14)
    .set('Lost', 15)
    .set('30th Anniversary', 15)
    .set('The Witch Queen', 16)
    .set('Risen', 16)
    .set('Haunted', 17)
    .set('Plunder', 18)
    .set('Seraph', 19)
    .set('Lightfall', 20)
    .set('Defiance', 20)
    .set('Deep', 21)
    .set('Witch', 22)
    .set('Wish', 23)
    .set('Final Shape', 24)
    .set('Echoes', 24)
    .set('Revenant', 25)
    .set('Heresy', 26)
    .set('Edge of Fate', 27)
    .set('Reclamation', 27);

exports.masterworks = [
    'Impact',
    'Range',
    'Stability',
    'Handling',
    'Reload',
    'Magazine',
    'Blast Radius',
    'Velocity',
    'Draw Time',
    'Charge',
    'Accuracy',
    'Shield Duration'
];

exports.sections = [
    'scopes',
    'sights',
    'barrels',
    'bowstrings',
    'hafts',
    'blades',
    'batteries',
    'magazines',
    'guards',
    'arrows',
    'trait1',
    'trait2',
    'origin',
    'origintrait',
    'grips',
    'stocks',
    'masterwork',
    'frames',
    'exotic',
    'exoticSp1',
    'exoticSp2',
    'mod'
];

//   TODO - TEMPORARY
// Migrating the armor quality code might be a good idea, but for now the queries will be hardcoded from the Excel File

// Queries generated by the Excel file on Dec 3 2024

// They are strings, but have them in Array form to be able to fold it in the IDE

const armorQueries = {
    //Vendors
    Titan: [
        99.996,
        'basestat:any:>=29) or (((basestat:mobility&resilience:>=26.5) or (basestat:mobility&recovery:>=26.5) or (basestat:mobility&discipline:>=26.5) or (basestat:mobility&intellect:>=26.5) or  (basestat:mobility&strength:>=26.5) or  (basestat:resilience&recovery:>=26.5) or (basestat:resilience&discipline:>=26.5) or (basestat:resilience&intellect:>=26.5) or (basestat:resilience&strength:>=26.5) or (basestat:recovery&discipline:>=26.5) or (basestat:recovery&intellect:>=26.5) or (basestat:recovery&strength:>=26.5) or (basestat:discipline&intellect:>=26.5) or (basestat:discipline&strength:>=26.5) or (basestat:intellect&strength:>=26.5)) -basestat:thirdhighest:>=17) or (((basestat:mobility&resilience&recovery:>=20 ) or (basestat:mobility&resilience&discipline:>=20 ) or (basestat:mobility&resilience&intellect:>=20 ) or (basestat:mobility&resilience&strength:>=20 ) or (basestat:mobility&recovery&discipline:>=20 ) or (basestat:mobility&recovery&intellect:>=20 ) or (basestat:mobility&recovery&strength:>=20 ) or (basestat:mobility&discipline&intellect:>=20 ) or (basestat:mobility&discipline&strength:>=20 ) or (basestat:mobility&intellect&strength:>=20 ) or (basestat:resilience&recovery&discipline:>=20 ) or (basestat:resilience&recovery&intellect:>=20 ) or (basestat:resilience&recovery&strength:>=20 ) or (basestat:resilience&discipline&intellect:>=20 ) or (basestat:resilience&discipline&strength:>=20 ) or (basestat:resilience&intellect&strength:>=20 ) or (basestat:recovery&discipline&intellect:>=20 ) or (basestat:recovery&discipline&strength:>=20 ) or (basestat:recovery&intellect&strength:>=20 ) or (basestat:discipline&intellect&strength:>=20 )) -basestat:fourthhighest:>=15) or (((basestat:mobility&resilience&recovery&intellect:>=15.5 ) or (basestat:mobility&resilience&recovery&discipline:>=15.5 ) or (basestat:mobility&resilience&recovery&strength:>=15.5 ) or (basestat:mobility&resilience&intellect&discipline:>=15.5 ) or (basestat:mobility&resilience&intellect&strength:>=15.5 ) or (basestat:mobility&resilience&discipline&strength:>=15.5 ) or (basestat:mobility&recovery&intellect&discipline:>=15.5 ) or (basestat:mobility&recovery&intellect&strength:>=15.5 ) or (basestat:mobility&recovery&discipline&strength:>=15.5 ) or (basestat:mobility&intellect&discipline&strength:>=15.5 ) or (basestat:resilience&recovery&intellect&discipline:>=15.5 ) or (basestat:resilience&recovery&intellect&strength:>=15.5 ) or (basestat:resilience&recovery&discipline&strength:>=15.5 ) or (basestat:resilience&intellect&discipline&strength:>=15.5 ) or (basestat:recovery&intellect&discipline&strength:>=15.5 )) -basestat:fifthhighest:>=12) or (((basestat:mobility&resilience&recovery&discipline&intellect:>=13) or (basestat:mobility&resilience&recovery&discipline&strength:>=13) or (basestat:mobility&resilience&recovery&intellect&strength:>=13) or (basestat:mobility&resilience&discipline&intellect&strength:>=13) or (basestat:mobility&recovery&discipline&intellect&strength:>=13) or (basestat:resilience&recovery&discipline&intellect&strength:>=13)) -basestat:sixthhighest:>=10'
    ],
    Warlock: [
        99.85,
        'basestat:any:>=28) or (((basestat:mobility&resilience:>=23.5) or (basestat:mobility&recovery:>=23.5) or (basestat:mobility&discipline:>=23.5) or (basestat:mobility&intellect:>=23.5) or  (basestat:mobility&strength:>=23.5) or  (basestat:resilience&recovery:>=23.5) or (basestat:resilience&discipline:>=23.5) or (basestat:resilience&intellect:>=23.5) or (basestat:resilience&strength:>=23.5) or (basestat:recovery&discipline:>=23.5) or (basestat:recovery&intellect:>=23.5) or (basestat:recovery&strength:>=23.5) or (basestat:discipline&intellect:>=23.5) or (basestat:discipline&strength:>=23.5) or (basestat:intellect&strength:>=23.5)) -basestat:thirdhighest:>=15) or (((basestat:mobility&resilience&recovery:>=18.33 ) or (basestat:mobility&resilience&discipline:>=18.33 ) or (basestat:mobility&resilience&intellect:>=18.33 ) or (basestat:mobility&resilience&strength:>=18.33 ) or (basestat:mobility&recovery&discipline:>=18.33 ) or (basestat:mobility&recovery&intellect:>=18.33 ) or (basestat:mobility&recovery&strength:>=18.33 ) or (basestat:mobility&discipline&intellect:>=18.33 ) or (basestat:mobility&discipline&strength:>=18.33 ) or (basestat:mobility&intellect&strength:>=18.33 ) or (basestat:resilience&recovery&discipline:>=18.33 ) or (basestat:resilience&recovery&intellect:>=18.33 ) or (basestat:resilience&recovery&strength:>=18.33 ) or (basestat:resilience&discipline&intellect:>=18.33 ) or (basestat:resilience&discipline&strength:>=18.33 ) or (basestat:resilience&intellect&strength:>=18.33 ) or (basestat:recovery&discipline&intellect:>=18.33 ) or (basestat:recovery&discipline&strength:>=18.33 ) or (basestat:recovery&intellect&strength:>=18.33 ) or (basestat:discipline&intellect&strength:>=18.33 )) -basestat:fourthhighest:>=13) or (((basestat:mobility&resilience&recovery&intellect:>=15 ) or (basestat:mobility&resilience&recovery&discipline:>=15 ) or (basestat:mobility&resilience&recovery&strength:>=15 ) or (basestat:mobility&resilience&intellect&discipline:>=15 ) or (basestat:mobility&resilience&intellect&strength:>=15 ) or (basestat:mobility&resilience&discipline&strength:>=15 ) or (basestat:mobility&recovery&intellect&discipline:>=15 ) or (basestat:mobility&recovery&intellect&strength:>=15 ) or (basestat:mobility&recovery&discipline&strength:>=15 ) or (basestat:mobility&intellect&discipline&strength:>=15 ) or (basestat:resilience&recovery&intellect&discipline:>=15 ) or (basestat:resilience&recovery&intellect&strength:>=15 ) or (basestat:resilience&recovery&discipline&strength:>=15 ) or (basestat:resilience&intellect&discipline&strength:>=15 ) or (basestat:recovery&intellect&discipline&strength:>=15 )) -basestat:fifthhighest:>=12) or (((basestat:mobility&resilience&recovery&discipline&intellect:>=12.6) or (basestat:mobility&resilience&recovery&discipline&strength:>=12.6) or (basestat:mobility&resilience&recovery&intellect&strength:>=12.6) or (basestat:mobility&resilience&discipline&intellect&strength:>=12.6) or (basestat:mobility&recovery&discipline&intellect&strength:>=12.6) or (basestat:resilience&recovery&discipline&intellect&strength:>=12.6)) -basestat:sixthhighest:>=10'
    ],
    Hunter: [
        99.2,
        'basestat:any:>=25) or (((basestat:mobility&resilience:>=21.5) or (basestat:mobility&recovery:>=21.5) or (basestat:mobility&discipline:>=21.5) or (basestat:mobility&intellect:>=21.5) or  (basestat:mobility&strength:>=21.5) or  (basestat:resilience&recovery:>=21.5) or (basestat:resilience&discipline:>=21.5) or (basestat:resilience&intellect:>=21.5) or (basestat:resilience&strength:>=21.5) or (basestat:recovery&discipline:>=21.5) or (basestat:recovery&intellect:>=21.5) or (basestat:recovery&strength:>=21.5) or (basestat:discipline&intellect:>=21.5) or (basestat:discipline&strength:>=21.5) or (basestat:intellect&strength:>=21.5)) -basestat:thirdhighest:>=14) or (((basestat:mobility&resilience&recovery:>=17.33 ) or (basestat:mobility&resilience&discipline:>=17.33 ) or (basestat:mobility&resilience&intellect:>=17.33 ) or (basestat:mobility&resilience&strength:>=17.33 ) or (basestat:mobility&recovery&discipline:>=17.33 ) or (basestat:mobility&recovery&intellect:>=17.33 ) or (basestat:mobility&recovery&strength:>=17.33 ) or (basestat:mobility&discipline&intellect:>=17.33 ) or (basestat:mobility&discipline&strength:>=17.33 ) or (basestat:mobility&intellect&strength:>=17.33 ) or (basestat:resilience&recovery&discipline:>=17.33 ) or (basestat:resilience&recovery&intellect:>=17.33 ) or (basestat:resilience&recovery&strength:>=17.33 ) or (basestat:resilience&discipline&intellect:>=17.33 ) or (basestat:resilience&discipline&strength:>=17.33 ) or (basestat:resilience&intellect&strength:>=17.33 ) or (basestat:recovery&discipline&intellect:>=17.33 ) or (basestat:recovery&discipline&strength:>=17.33 ) or (basestat:recovery&intellect&strength:>=17.33 ) or (basestat:discipline&intellect&strength:>=17.33 )) -basestat:fourthhighest:>=12) or (((basestat:mobility&resilience&recovery&intellect:>=14.75 ) or (basestat:mobility&resilience&recovery&discipline:>=14.75 ) or (basestat:mobility&resilience&recovery&strength:>=14.75 ) or (basestat:mobility&resilience&intellect&discipline:>=14.75 ) or (basestat:mobility&resilience&intellect&strength:>=14.75 ) or (basestat:mobility&resilience&discipline&strength:>=14.75 ) or (basestat:mobility&recovery&intellect&discipline:>=14.75 ) or (basestat:mobility&recovery&intellect&strength:>=14.75 ) or (basestat:mobility&recovery&discipline&strength:>=14.75 ) or (basestat:mobility&intellect&discipline&strength:>=14.75 ) or (basestat:resilience&recovery&intellect&discipline:>=14.75 ) or (basestat:resilience&recovery&intellect&strength:>=14.75 ) or (basestat:resilience&recovery&discipline&strength:>=14.75 ) or (basestat:resilience&intellect&discipline&strength:>=14.75 ) or (basestat:recovery&intellect&discipline&strength:>=14.75 )) -basestat:fifthhighest:>=11) or (((basestat:mobility&resilience&recovery&discipline&intellect:>=12.4) or (basestat:mobility&resilience&recovery&discipline&strength:>=12.4) or (basestat:mobility&resilience&recovery&intellect&strength:>=12.4) or (basestat:mobility&resilience&discipline&intellect&strength:>=12.4) or (basestat:mobility&recovery&discipline&intellect&strength:>=12.4) or (basestat:resilience&recovery&discipline&intellect&strength:>=12.4)) -basestat:sixthhighest:>=10'
    ],
    //Vault
    Junk: [
        90.0,
        '/* Armor Cleanup */ is:armor not:classitem not:exotic ( ( -modslot:artifice -source:fotl -notes:IB -( basestat:any:>=19 ) -( ((basestat:mobility&resilience:>=18) or (basestat:mobility&recovery:>=18) or (basestat:mobility&discipline:>=18) or (basestat:mobility&intellect:>=18) or  (basestat:mobility&strength:>=18) or  (basestat:resilience&recovery:>=18) or (basestat:resilience&discipline:>=18) or (basestat:resilience&intellect:>=18) or (basestat:resilience&strength:>=18) or (basestat:recovery&discipline:>=18) or (basestat:recovery&intellect:>=18) or (basestat:recovery&strength:>=18) or (basestat:discipline&intellect:>=18) or (basestat:discipline&strength:>=18) or (basestat:intellect&strength:>=18)) -basestat:thirdhighest:>=12 ) -( ((basestat:mobility&resilience&recovery:>=15.33 ) or (basestat:mobility&resilience&discipline:>=15.33 ) or (basestat:mobility&resilience&intellect:>=15.33 ) or (basestat:mobility&resilience&strength:>=15.33 ) or (basestat:mobility&recovery&discipline:>=15.33 ) or (basestat:mobility&recovery&intellect:>=15.33 ) or (basestat:mobility&recovery&strength:>=15.33 ) or (basestat:mobility&discipline&intellect:>=15.33 ) or (basestat:mobility&discipline&strength:>=15.33 ) or (basestat:mobility&intellect&strength:>=15.33 ) or (basestat:resilience&recovery&discipline:>=15.33 ) or (basestat:resilience&recovery&intellect:>=15.33 ) or (basestat:resilience&recovery&strength:>=15.33 ) or (basestat:resilience&discipline&intellect:>=15.33 ) or (basestat:resilience&discipline&strength:>=15.33 ) or (basestat:resilience&intellect&strength:>=15.33 ) or (basestat:recovery&discipline&intellect:>=15.33 ) or (basestat:recovery&discipline&strength:>=15.33 ) or (basestat:recovery&intellect&strength:>=15.33 ) or (basestat:discipline&intellect&strength:>=15.33 )) -basestat:fourthhighest:>=11 ) -( ((basestat:mobility&resilience&recovery&intellect:>=13.5 ) or (basestat:mobility&resilience&recovery&discipline:>=13.5 ) or (basestat:mobility&resilience&recovery&strength:>=13.5 ) or (basestat:mobility&resilience&intellect&discipline:>=13.5 ) or (basestat:mobility&resilience&intellect&strength:>=13.5 ) or (basestat:mobility&resilience&discipline&strength:>=13.5 ) or (basestat:mobility&recovery&intellect&discipline:>=13.5 ) or (basestat:mobility&recovery&intellect&strength:>=13.5 ) or (basestat:mobility&recovery&discipline&strength:>=13.5 ) or (basestat:mobility&intellect&discipline&strength:>=13.5 ) or (basestat:resilience&recovery&intellect&discipline:>=13.5 ) or (basestat:resilience&recovery&intellect&strength:>=13.5 ) or (basestat:resilience&recovery&discipline&strength:>=13.5 ) or (basestat:resilience&intellect&discipline&strength:>=13.5 ) or (basestat:recovery&intellect&discipline&strength:>=13.5 )) -basestat:fifthhighest:>=10 ) -( ((basestat:mobility&resilience&recovery&discipline&intellect:>=11.6) or (basestat:mobility&resilience&recovery&discipline&strength:>=11.6) or (basestat:mobility&resilience&recovery&intellect&strength:>=11.6) or (basestat:mobility&resilience&discipline&intellect&strength:>=11.6) or (basestat:mobility&recovery&discipline&intellect&strength:>=11.6) or (basestat:resilience&recovery&discipline&intellect&strength:>=11.6)) -basestat:sixthhighest:>=9 ) ) or ( modslot:artifice -( basestat:any:>=16 ) -( ((basestat:mobility&resilience:>=16.5) or (basestat:mobility&recovery:>=16.5) or (basestat:mobility&discipline:>=16.5) or (basestat:mobility&intellect:>=16.5) or  (basestat:mobility&strength:>=16.5) or  (basestat:resilience&recovery:>=16.5) or (basestat:resilience&discipline:>=16.5) or (basestat:resilience&intellect:>=16.5) or (basestat:resilience&strength:>=16.5) or (basestat:recovery&discipline:>=16.5) or (basestat:recovery&intellect:>=16.5) or (basestat:recovery&strength:>=16.5) or (basestat:discipline&intellect:>=16.5) or (basestat:discipline&strength:>=16.5) or (basestat:intellect&strength:>=16.5)) -basestat:thirdhighest:>=11 ) -( ((basestat:mobility&resilience&recovery:>=14.33 ) or (basestat:mobility&resilience&discipline:>=14.33 ) or (basestat:mobility&resilience&intellect:>=14.33 ) or (basestat:mobility&resilience&strength:>=14.33 ) or (basestat:mobility&recovery&discipline:>=14.33 ) or (basestat:mobility&recovery&intellect:>=14.33 ) or (basestat:mobility&recovery&strength:>=14.33 ) or (basestat:mobility&discipline&intellect:>=14.33 ) or (basestat:mobility&discipline&strength:>=14.33 ) or (basestat:mobility&intellect&strength:>=14.33 ) or (basestat:resilience&recovery&discipline:>=14.33 ) or (basestat:resilience&recovery&intellect:>=14.33 ) or (basestat:resilience&recovery&strength:>=14.33 ) or (basestat:resilience&discipline&intellect:>=14.33 ) or (basestat:resilience&discipline&strength:>=14.33 ) or (basestat:resilience&intellect&strength:>=14.33 ) or (basestat:recovery&discipline&intellect:>=14.33 ) or (basestat:recovery&discipline&strength:>=14.33 ) or (basestat:recovery&intellect&strength:>=14.33 ) or (basestat:discipline&intellect&strength:>=14.33 )) -basestat:fourthhighest:>=10 ) -( ((basestat:mobility&resilience&recovery&intellect:>=12.75 ) or (basestat:mobility&resilience&recovery&discipline:>=12.75 ) or (basestat:mobility&resilience&recovery&strength:>=12.75 ) or (basestat:mobility&resilience&intellect&discipline:>=12.75 ) or (basestat:mobility&resilience&intellect&strength:>=12.75 ) or (basestat:mobility&resilience&discipline&strength:>=12.75 ) or (basestat:mobility&recovery&intellect&discipline:>=12.75 ) or (basestat:mobility&recovery&intellect&strength:>=12.75 ) or (basestat:mobility&recovery&discipline&strength:>=12.75 ) or (basestat:mobility&intellect&discipline&strength:>=12.75 ) or (basestat:resilience&recovery&intellect&discipline:>=12.75 ) or (basestat:resilience&recovery&intellect&strength:>=12.75 ) or (basestat:resilience&recovery&discipline&strength:>=12.75 ) or (basestat:resilience&intellect&discipline&strength:>=12.75 ) or (basestat:recovery&intellect&discipline&strength:>=12.75 )) -basestat:fifthhighest:>=10 ) -( ((basestat:mobility&resilience&recovery&discipline&intellect:>=11) or (basestat:mobility&resilience&recovery&discipline&strength:>=11) or (basestat:mobility&resilience&recovery&intellect&strength:>=11) or (basestat:mobility&resilience&discipline&intellect&strength:>=11) or (basestat:mobility&recovery&discipline&intellect&strength:>=11) or (basestat:resilience&recovery&discipline&intellect&strength:>=11)) -basestat:sixthhighest:>=9 ) ) or ( notes:IB -( basestat:any:>=17 ) -( ((basestat:mobility&resilience:>=17) or (basestat:mobility&recovery:>=17) or (basestat:mobility&discipline:>=17) or (basestat:mobility&intellect:>=17) or  (basestat:mobility&strength:>=17) or  (basestat:resilience&recovery:>=17) or (basestat:resilience&discipline:>=17) or (basestat:resilience&intellect:>=17) or (basestat:resilience&strength:>=17) or (basestat:recovery&discipline:>=17) or (basestat:recovery&intellect:>=17) or (basestat:recovery&strength:>=17) or (basestat:discipline&intellect:>=17) or (basestat:discipline&strength:>=17) or (basestat:intellect&strength:>=17)) -basestat:thirdhighest:>=11 ) -( ((basestat:mobility&resilience&recovery:>=14.6633333333333 ) or (basestat:mobility&resilience&discipline:>=14.6633333333333 ) or (basestat:mobility&resilience&intellect:>=14.6633333333333 ) or (basestat:mobility&resilience&strength:>=14.6633333333333 ) or (basestat:mobility&recovery&discipline:>=14.6633333333333 ) or (basestat:mobility&recovery&intellect:>=14.6633333333333 ) or (basestat:mobility&recovery&strength:>=14.6633333333333 ) or (basestat:mobility&discipline&intellect:>=14.6633333333333 ) or (basestat:mobility&discipline&strength:>=14.6633333333333 ) or (basestat:mobility&intellect&strength:>=14.6633333333333 ) or (basestat:resilience&recovery&discipline:>=14.6633333333333 ) or (basestat:resilience&recovery&intellect:>=14.6633333333333 ) or (basestat:resilience&recovery&strength:>=14.6633333333333 ) or (basestat:resilience&discipline&intellect:>=14.6633333333333 ) or (basestat:resilience&discipline&strength:>=14.6633333333333 ) or (basestat:resilience&intellect&strength:>=14.6633333333333 ) or (basestat:recovery&discipline&intellect:>=14.6633333333333 ) or (basestat:recovery&discipline&strength:>=14.6633333333333 ) or (basestat:recovery&intellect&strength:>=14.6633333333333 ) or (basestat:discipline&intellect&strength:>=14.6633333333333 )) -basestat:fourthhighest:>=10 ) -( ((basestat:mobility&resilience&recovery&intellect:>=13 ) or (basestat:mobility&resilience&recovery&discipline:>=13 ) or (basestat:mobility&resilience&recovery&strength:>=13 ) or (basestat:mobility&resilience&intellect&discipline:>=13 ) or (basestat:mobility&resilience&intellect&strength:>=13 ) or (basestat:mobility&resilience&discipline&strength:>=13 ) or (basestat:mobility&recovery&intellect&discipline:>=13 ) or (basestat:mobility&recovery&intellect&strength:>=13 ) or (basestat:mobility&recovery&discipline&strength:>=13 ) or (basestat:mobility&intellect&discipline&strength:>=13 ) or (basestat:resilience&recovery&intellect&discipline:>=13 ) or (basestat:resilience&recovery&intellect&strength:>=13 ) or (basestat:resilience&recovery&discipline&strength:>=13 ) or (basestat:resilience&intellect&discipline&strength:>=13 ) or (basestat:recovery&intellect&discipline&strength:>=13 )) -basestat:fifthhighest:>=10 ) -( ((basestat:mobility&resilience&recovery&discipline&intellect:>=11.2) or (basestat:mobility&resilience&recovery&discipline&strength:>=11.2) or (basestat:mobility&resilience&recovery&intellect&strength:>=11.2) or (basestat:mobility&resilience&discipline&intellect&strength:>=11.2) or (basestat:mobility&recovery&discipline&intellect&strength:>=11.2) or (basestat:resilience&recovery&discipline&intellect&strength:>=11.2)) -basestat:sixthhighest:>=9 ) ) )'
    ]
};

exports.vendorArmorQuery = `/* Vendor Top Armor */  (is:exotic is:classitem) or (basestat:total:>=60 ((is:Titan (${armorQueries.Titan[1]})) or (is:Warlock (${armorQueries.Warlock[1]})) or (is:Hunter (${armorQueries.Hunter[1]}))))`;

exports.vaultArmorQuery = armorQueries.Junk[1];
